name: Build and Deploy to Azure
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push API Docker image
        run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/dental-api:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/dental-api:${{ github.sha }}
      - name: Deploy API to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: dental-api
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/dental-api:${{ github.sha }}
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push Frontend Docker image
        run: |
          cd frontend
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/dental-frontend:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/dental-frontend:${{ github.sha }}
      - name: Deploy Frontend to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: dental-frontend
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/dental-frontend:${{ github.sha }}